src/Entity/User/Owner.php
<?php

namespace App\Entity\User;

use App\Entity\Property\Property;
use App\Repository\User\OwnerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OwnerRepository::class)
 */
class Owner extends User
{
    /**
     * @ORM\OneToMany(targetEntity=Property::class, mappedBy="owner_property")
     */
    private $owner_properties;

    /**
     * @ORM\ManyToOne(targetEntity=Agent::class, inversedBy="owners")
     */
    private $agent;

    public function __construct()
    {
        parent::__construct();
        $this->owner_properties = new ArrayCollection();
    }

    /**
     * @return Collection|Property[]
     */
    public function getOwnerProperties(): Collection
    {
        return $this->owner_properties;
    }

    public function addOwnerProperty(Property $ownerProperty): self
    {
        if (!$this->owner_properties->contains($ownerProperty)) {
            $this->owner_properties[] = $ownerProperty;
            $ownerProperty->setOwnerProperty($this);
        }

        return $this;
    }

    public function removeOwnerProperty(Property $ownerProperty): self
    {
        if ($this->owner_properties->removeElement($ownerProperty)) {
            // set the owning side to null (unless already changed)
            if ($ownerProperty->getOwnerProperty() === $this) {
                $ownerProperty->setOwnerProperty(null);
            }
        }

        return $this;
    }

    public function getAgent(): ?Agent
    {
        return $this->agent;
    }

    public function setAgent(?Agent $agent): self
    {
        $this->agent = $agent;

        return $this;
    }
}

src/Entity/User/User.php
<?php

namespace App\Entity\User;

use App\Entity\Document;
use App\Entity\Document\DocHasSeen;
use App\Entity\Message\Message;
use App\Entity\Message\UserHasMessageRead;
use App\Entity\Property\Property;
use App\Repository\User\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "private_owner" = "PrivateOwner", "owner" = "Owner", "agent" = "Agent", "tenant" = "Tenant"})
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="json")
     */
    protected $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    protected $password;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $firstname;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $lastname;

    /**
     * @ORM\Column(type="string", length=20)
     */
    protected $phone_number;

    /**
     * @var \DateTimeImmutable $created_at
     * 
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    protected $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $address;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_active = true;

    /**
     * @ORM\OneToMany(targetEntity=DocHasSeen::class, mappedBy="user", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity=Property::class, mappedBy="manager_property")
     */
    protected $manager_properties;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="sender")
     */
    protected $sender_messages;

    /**
     * @ORM\OneToMany(targetEntity=UserHasMessageRead::class, mappedBy="recipient")
     */
    protected $user_recipient_messages;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->manager_properties = new ArrayCollection();
        $this->sender_messages = new ArrayCollection();
        $this->user_recipient_messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection|DocHasSeen[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(DocHasSeen $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setUser($this);
        }

        return $this;
    }

    public function removeDocument(DocHasSeen $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getUser() === $this) {
                $document->setUser(null);
            }
        }

        return $this;
    }
    
    public function __toString()
    {
        return $this->lastname . ' ' . $this->firstname . ' ' . $this->id;
    }

    /**
     * @return Collection|Property[]
     */
    public function getManagerProperties(): Collection
    {
        return $this->manager_properties;
    }

    public function addManagerProperty(Property $managerProperty): self
    {
        if (!$this->manager_properties->contains($managerProperty)) {
            $this->manager_properties[] = $managerProperty;
            $managerProperty->setManagerProperty($this);
        }

        return $this;
    }

    public function removeManagerProperty(Property $managerProperty): self
    {
        if ($this->manager_properties->removeElement($managerProperty)) {
            // set the owning side to null (unless already changed)
            if ($managerProperty->getManagerProperty() === $this) {
                $managerProperty->setManagerProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getSenderMessages(): Collection
    {
        return $this->sender_messages;
    }

    public function addSenderMessage(Message $senderMessage): self
    {
        if (!$this->sender_messages->contains($senderMessage)) {
            $this->sender_messages[] = $senderMessage;
            $senderMessage->setSender($this);
        }

        return $this;
    }

    public function removeSenderMessage(Message $senderMessage): self
    {
        if ($this->sender_messages->removeElement($senderMessage)) {
            // set the owning side to null (unless already changed)
            if ($senderMessage->getSender() === $this) {
                $senderMessage->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserHasMessageRead[]
     */
    public function getUserRecipientMessages(): Collection
    {
        return $this->user_recipient_messages;
    }

    public function addUserRecipientMessage(UserHasMessageRead $userRecipientMessage): self
    {
        if (!$this->user_recipient_messages->contains($userRecipientMessage)) {
            $this->user_recipient_messages[] = $userRecipientMessage;
            $userRecipientMessage->setRecipient($this);
        }

        return $this;
    }

    public function removeUserRecipientMessage(UserHasMessageRead $userRecipientMessage): self
    {
        if ($this->user_recipient_messages->removeElement($userRecipientMessage)) {
            // set the owning side to null (unless already changed)
            if ($userRecipientMessage->getRecipient() === $this) {
                $userRecipientMessage->setRecipient(null);
            }
        }

        return $this;
    }

}

src/Controller/Page/OwnerController.php
<?php

namespace App\Controller\Page;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OwnerController extends AbstractController
{
    /**
     * @Route("/page/owner/information", name="page_owner_information")
     */
    public function information(): Response
    {
        return $this->render('page/owner/information.html.twig', [
            'active' => 'owner'
        ]);
    }
}

src/Controller/PrivateArea/CalendarController.php
<?php

namespace App\Controller\PrivateArea;

use App\Entity\Calendar;
use App\Repository\CalendarRepository;
use App\Service\CalendarManagerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/private-area/calendar", name="private_area_calendar_")
 */
class CalendarController extends AbstractController
{
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/", name="list")
     */
    public function list(CalendarManagerService $calendarManager): Response
    {
        $data = $calendarManager->getAllDatas($this->getUser());

        return $this->render('private_area/calendar/list.html.twig', [
            'navigationPrivate' => true,
            'data' => $data,
            'active' => 'calendar'
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"POST"})
     */
    public function edit(Request $request, Calendar $calendar, CalendarManagerService $calendarManager): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        if ($request->isMethod('POST')) {
            $calendarManager->editRemind($calendar, $request, $calendar->getTenant());
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been changed successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/edit-all/{id}/{repeatId}", name="edit_all", methods={"POST"})
     */
    public function editAll(Calendar $calendar, $repeatId, Request $request, CalendarManagerService $calendarManager): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        if ($request->isMethod('POST')) {
            $calendarManager->editRemindAll($repeatId, $request, $calendar->getTenant());
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been changed successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/delete/{id}", name="delete", methods={"POST"})
     */
    public function delete(Calendar $calendar, CalendarManagerService $calendarManager, Request $request): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        $submittedToken = $request->request->get('delete_token');
        if ($this->isCsrfTokenValid('delete-reminder', $submittedToken)) {
            $calendarManager->deleteRemind($calendar);
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been deleted successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/delete-all/{id}/{repeatId}", name="delete_all", methods={"POST"})
     */
    public function deleteAll(Calendar $calendar, $repeatId, CalendarManagerService $calendarManager, Request $request): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        $submittedToken = $request->request->get('delete_token');
        if ($this->isCsrfTokenValid('delete-reminder', $submittedToken)) {
            $calendarManager->deleteRemindAll($repeatId);
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('All reminders have been deleted successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }

        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }
}

templates/private_area/owner/email.html.twig
<div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
  <h1>{{ 'creation of your tenant account'|trans|capitalize }}</h1>
  <h4>{{ 'from'|trans|capitalize }} : {{ mail }}</h4>
  <br>
	<h4>{{ 'subject'|trans|capitalize }} : {{ subject }}</h4>
	<br>
	<h5>{{ 'your login details'|trans|capitalize }} :</h5>
  <p><strong>{{ 'username' }} : </strong>{{ username }}</p>
  <p><strong>{{ 'password' }} : </strong>{{ password }}</p>
  <br>
  <p>{{ 'welcome'|trans|capitalize }} !</p>
</div>

templates/private_area/owner/list.html.twig
{% extends 'base.html.twig' %} {% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
	{% for message in app.flashes('message_alert') %}
    {{ include('include/_alert.html.twig') }}
  {% endfor %}
	<h2>{{'owners'|trans|capitalize}}</h2>
  <div class="actions-buttons-group">
		<a href="{{ path('private_area_owner_new') }}" class="button button-small"><i class="fa fa-plus-circle"></i>&nbsp;{{ 'add new'|trans }}</a>
	</div>
	<div class="private-area-scroll-container">
			<table>
				<thead>
					<tr>
						{% for k, header in headers %}
							{% if header.header %}
								<th>
									<div class="header-btn-sort-group">
										{{ header.label|trans|capitalize }}
										{% if header.sort %}
											<div class="table-sort-buttons">
												<a href="{{ path('private_area_owner_list', {sortBy: k, order: 'desc'}) }}"><i class="fa fa-caret-up" title="{{ 'descending sort'|trans|capitalize }}"></i></a>
												<a href="{{ path('private_area_owner_list', {sortBy: k, order: 'asc'}) }}"><i class="fa fa-caret-down" title="{{ 'ascending sort'|trans|capitalize }}"></i></a>
											</div>
										{% endif %}
									</div>
								</th>
							{% endif %}
						{% endfor %}
					</tr>
				</thead>
				<tbody>
					{% for owner in datas %}
						<tr>
							<td>{{ owner.lastname|capitalize }}</td>
							<td>{{ owner.firstname|capitalize }}</td>
							<td>{{ owner.id }}</td>
							<td>
								<div class="table-td-actions">
									<a href="{{ path('private_area_owner_view', {id: owner.id}) }}" title="{{ 'see owner information'|trans|capitalize }}"><i class="fa fa-eye"></i></a>
								</div>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% if datas|length > 0 %}
			{% if datas.getTotalItemCount > 10 %}
				{{ knp_pagination_render(datas) }}
			{% endif %}
		{% endif %}
	</div>
</main>
<div class="modal" id="modal-confirm-delete" role="dialog">
	<div class="modal-content w-450">
		<a href="#" class="modal-close fa fa-close" role="button" data-dismiss="dialog"></a>
		<div class="modal-header">
		<h3><i class="fa fa-warning"></i>&nbsp;{{ 'confirm deletion'|trans|capitalize }}</h3>
		</div>
		<div class="modal-body">
			<p>{{ 'you are about to delete property ad from property no'|trans|capitalize }}&nbsp;<span class="span-item-id"></span>.</p>
			<br>
			<p>{{ 'this action is irreversible.'|trans|capitalize }}</p>
		</div>
		<div class="modal-footer">
			<button class="button button-rounded button-outline" role="button" data-dismiss="dialog"><i class="fa fa-close"></i>&nbsp;{{'cancel'|trans}}</button>
			<a id="delete-button" role="button" class="button button-rounded"><i class="fa fa-check"></i>&nbsp;{{'confirm'|trans}}</a>
		</div>
	</div>
</div>
{% endblock %}

templates/private_area/owner/new.html.twig
{% extends 'base.html.twig' %} 

{% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
  {{ form_start(form, {'attr': {'class': 'private-area-form'}}) }}
    <h1>{{'create new owner'|trans|upper}}</h1>
    <div class="form-control-group">
      {{ form_label(form.firstname, null, {'label': 'firstname'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.firstname) }}
    </div>
    <div class="form-control-group">
      {{ form_label(form.lastname, null, {'label': 'lastname'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.lastname) }}
    </div>
    <div class="form-control-group">
      {{ form_label(form.email, null, {'label': 'email'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.email) }}
    </div>
    <div class="form-control-group">
      {{ form_label(form.address, null, {'label': 'address'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.address) }}
    </div>
    <div class="form-control-group">
      {{ form_label(form.phone_number, null, {'label': 'phone number'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.phone_number) }}
    </div> 
    <div class="form-button-submit-between">
      <a href="{{ path('private_area_owner_list') }}" class="button button-rounded"><i class="fa fa-arrow-left"></i>&nbsp;{{ 'back to list'|trans }}</a>
      <button type="submit" class="button button-rounded button-outline"><i class="fa fa-check"></i>&nbsp;{{'create'|trans}}</button>
    </div>
  {{ form_end(form) }}
</main>
{% endblock %}

templates/private_area/owner/view.html.twig
{% extends 'base.html.twig' %} 

{% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
	{% for message in app.flashes('message_alert') %}
    {{ include('include/_alert.html.twig') }}
  {% endfor %}
	<h2>{{'owner no'|trans|capitalize}}&nbsp;{{ owner.id }}</h2>
	<div class="view-informations">
		<div class="view-informations-group-1">
			<h3><i class="fa fa-user"></i>&nbsp;{{ 'personal informations'|trans|capitalize }} :</h3>
			<ul>
				<li><strong>{{ 'lastname'|trans|capitalize }} : </strong>{{ owner.lastname }}</li>
				<li><strong>{{ 'firstname'|trans|capitalize }} : </strong>{{ owner.firstname }}</li>
				<li><strong>{{ 'address'|trans|capitalize }} : </strong>{{ owner.address }}</li>
				<li><strong>{{ 'email'|trans|capitalize }} : </strong>{{ owner.email }}</li>
				<li><strong>{{ 'phone number'|trans|capitalize }} : </strong>{{ owner.phoneNumber }}</li>
			</ul>
		</div>
		<div class="view-informations-group-2">
			<h3><i class="fa fa-building"></i>&nbsp;{{ 'properties informations'|trans|capitalize }} :</h3>
			<ul>
				<li><strong>{{ 'number of properties'|trans|capitalize }} : </strong>{{ owner.ownerProperties|length }}</li>
				<li><strong>{{ 'number of properties rented'|trans|capitalize }} : </strong></li>
			</ul>
		</div>
		<div class="form-button-submit-right">
			<a href="{{ path('private_area_owner_list') }}" class="button button-rounded button-small"><i class="fa fa-arrow-left"></i>&nbsp;{{ 'back to list'|trans }}</a>
		</div>
	</div>
</main>
{% endblock %}