src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=OfferRepository::class)
 */
class Offer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=64)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Property::class, inversedBy="offers")
     */
    private $property;

    /**
     * @var \DateTimeImmutable $created_at
     * 
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @var \DateTimeImmutable $updated_at
     * 
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }
}

src/Entity/User/User.php
<?php

namespace App\Entity\User;

use App\Entity\Document;
use App\Entity\Document\DocHasSeen;
use App\Entity\Message\Message;
use App\Entity\Message\UserHasMessageRead;
use App\Entity\Property\Property;
use App\Repository\User\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "private_owner" = "PrivateOwner", "owner" = "Owner", "agent" = "Agent", "tenant" = "Tenant"})
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="json")
     */
    protected $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    protected $password;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $firstname;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $lastname;

    /**
     * @ORM\Column(type="string", length=20)
     */
    protected $phone_number;

    /**
     * @var \DateTimeImmutable $created_at
     * 
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    protected $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $address;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $is_active = true;

    /**
     * @ORM\OneToMany(targetEntity=DocHasSeen::class, mappedBy="user", orphanRemoval=true)
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity=Property::class, mappedBy="manager_property")
     */
    protected $manager_properties;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="sender")
     */
    protected $sender_messages;

    /**
     * @ORM\OneToMany(targetEntity=UserHasMessageRead::class, mappedBy="recipient")
     */
    protected $user_recipient_messages;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->manager_properties = new ArrayCollection();
        $this->sender_messages = new ArrayCollection();
        $this->user_recipient_messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection|DocHasSeen[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(DocHasSeen $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setUser($this);
        }

        return $this;
    }

    public function removeDocument(DocHasSeen $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getUser() === $this) {
                $document->setUser(null);
            }
        }

        return $this;
    }
    
    public function __toString()
    {
        return $this->lastname . ' ' . $this->firstname . ' ' . $this->id;
    }

    /**
     * @return Collection|Property[]
     */
    public function getManagerProperties(): Collection
    {
        return $this->manager_properties;
    }

    public function addManagerProperty(Property $managerProperty): self
    {
        if (!$this->manager_properties->contains($managerProperty)) {
            $this->manager_properties[] = $managerProperty;
            $managerProperty->setManagerProperty($this);
        }

        return $this;
    }

    public function removeManagerProperty(Property $managerProperty): self
    {
        if ($this->manager_properties->removeElement($managerProperty)) {
            // set the owning side to null (unless already changed)
            if ($managerProperty->getManagerProperty() === $this) {
                $managerProperty->setManagerProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getSenderMessages(): Collection
    {
        return $this->sender_messages;
    }

    public function addSenderMessage(Message $senderMessage): self
    {
        if (!$this->sender_messages->contains($senderMessage)) {
            $this->sender_messages[] = $senderMessage;
            $senderMessage->setSender($this);
        }

        return $this;
    }

    public function removeSenderMessage(Message $senderMessage): self
    {
        if ($this->sender_messages->removeElement($senderMessage)) {
            // set the owning side to null (unless already changed)
            if ($senderMessage->getSender() === $this) {
                $senderMessage->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserHasMessageRead[]
     */
    public function getUserRecipientMessages(): Collection
    {
        return $this->user_recipient_messages;
    }

    public function addUserRecipientMessage(UserHasMessageRead $userRecipientMessage): self
    {
        if (!$this->user_recipient_messages->contains($userRecipientMessage)) {
            $this->user_recipient_messages[] = $userRecipientMessage;
            $userRecipientMessage->setRecipient($this);
        }

        return $this;
    }

    public function removeUserRecipientMessage(UserHasMessageRead $userRecipientMessage): self
    {
        if ($this->user_recipient_messages->removeElement($userRecipientMessage)) {
            // set the owning side to null (unless already changed)
            if ($userRecipientMessage->getRecipient() === $this) {
                $userRecipientMessage->setRecipient(null);
            }
        }

        return $this;
    }

}

src/Form/PrivateArea/DocumentManageUsersAccessFormType.php
<?php

namespace App\Form\PrivateArea;

use App\Entity\Document\DocHasSeen;
use App\Entity\Document\Document;
use App\Repository\User\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DocumentManageUsersAccessFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('users', EntityType::class, [
                'class' => DocHasSeen::class,
                'choice_label' => 'user',
                'multiple' => true,
                'required' => false,
                'by_reference' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Document::class
        ]);
    }
}

src/Controller/PrivateArea/CalendarController.php
<?php

namespace App\Controller\PrivateArea;

use App\Entity\Calendar;
use App\Repository\CalendarRepository;
use App\Service\CalendarManagerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/private-area/calendar", name="private_area_calendar_")
 */
class CalendarController extends AbstractController
{
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/", name="list")
     */
    public function list(CalendarManagerService $calendarManager): Response
    {
        $data = $calendarManager->getAllDatas($this->getUser());

        return $this->render('private_area/calendar/list.html.twig', [
            'navigationPrivate' => true,
            'data' => $data,
            'active' => 'calendar'
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"POST"})
     */
    public function edit(Request $request, Calendar $calendar, CalendarManagerService $calendarManager): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        if ($request->isMethod('POST')) {
            $calendarManager->editRemind($calendar, $request, $calendar->getTenant());
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been changed successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/edit-all/{id}/{repeatId}", name="edit_all", methods={"POST"})
     */
    public function editAll(Calendar $calendar, $repeatId, Request $request, CalendarManagerService $calendarManager): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        if ($request->isMethod('POST')) {
            $calendarManager->editRemindAll($repeatId, $request, $calendar->getTenant());
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been changed successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/delete/{id}", name="delete", methods={"POST"})
     */
    public function delete(Calendar $calendar, CalendarManagerService $calendarManager, Request $request): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        $submittedToken = $request->request->get('delete_token');
        if ($this->isCsrfTokenValid('delete-reminder', $submittedToken)) {
            $calendarManager->deleteRemind($calendar);
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('The remind has been deleted successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }
        
        
        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/delete-all/{id}/{repeatId}", name="delete_all", methods={"POST"})
     */
    public function deleteAll(Calendar $calendar, $repeatId, CalendarManagerService $calendarManager, Request $request): Response
    {
        $tenantId = $calendar->getTenant()->getId();
        $submittedToken = $request->request->get('delete_token');
        if ($this->isCsrfTokenValid('delete-reminder', $submittedToken)) {
            $calendarManager->deleteRemindAll($repeatId);
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('All reminders have been deleted successfully'), 
                'style' => 'success'
            ]);
        } else {
            $this->addFlash('message_alert', [
                'text' => $this->translator->trans('An error occurred, please try again later'), 
                'style' => 'danger'
            ]);
        }

        return $this->redirectToRoute('private_area_tenant_calendar', ['id' => $tenantId], Response::HTTP_SEE_OTHER);
    }
}

templates/private_area/_filter.html.twig
<div class="filter-group">
	<form action="{{ path('private_area_' ~ entity ~ '_list_sorted') }}" method="POST">
		<div class="filter-list-group" id="filter-list-group">
			<a href="#" class="modal-close fa fa-close" role="button" data-dismiss="close"></a>
			<h6><i class="fa fa-filter"></i>&nbsp;{{ 'filter'|trans|capitalize }}</h6>
			<div class="filter-top-button-group">
				<a href="{{ path('private_area_' ~ entity ~ '_list') }}" class="button button-small button-tiny" id="button-clear-filters">{{ 'clear'|trans|capitalize }}</a>
				<button type="submit" class="button button-small button-tiny">{{ 'validate'|trans|capitalize }}</button>
			</div>
			<ul>
				{% for k, header in headers %}
					{% if header.filter %}
						<li>
							<div class="input-checkbox-group">
								<input type="checkbox" id="{{ header.label }}" data-header="{{ k }}">
								<label for="{{ header.label }}">
									<span><i class="fa fa-check"></i></span>
									{{ header.label|trans|capitalize }}&nbsp;
									{% if app.request.session.get('filter_criterias') != null %}
										{% if app.request.session.get('filter_criterias').get(k) != null %}
											{% set countItemsFiltered = 0 %}
											{% for key, item in app.request.session.get('filter_criterias').get(k)|filter(item => item != '') %}
												{% set countItemsFiltered = countItemsFiltered + 1 %}
											{% endfor %}
											{% if countItemsFiltered > 0 %}
												({{ countItemsFiltered }})
											{% endif %}
										{% endif %}
									{% endif %}
								</label>
							</div>
							{% if header.type == 'checkbox' %}
								<ul>
									{% for index, value in header.values %}
									{% set checked = '' %}
									{% if app.request.session.get('filter_criterias') != null %}
										{% if app.request.session.get('filter_criterias').get(k) != null %}
											{% if value[k] in app.request.session.get('filter_criterias').get(k) %}
												{% set checked = 'checked' %}
											{% endif %}
										{% endif %}
									{% endif %}
										<li>
											<div class="input-checkbox-group">
												<input type="checkbox" id="{{ k~'_'~value[k] }}" name="{{ k }}[]" value="{{ value[k] }}" {{ checked }}>
												<label for="{{ k~'_'~value[k] }}"><span><i class="fa fa-check"></i></span>{{ value[k]|trans|capitalize }}</label>
											</div>
										</li>
									{% endfor %}
								</ul>
							{% elseif header.type == 'number' %}
								<ul class="input-filter-number-group">
									<li>
										<label for="{{ k~'_Min' }}">Min</label>
										{% set inputMinValue = '' %}
										{% if app.request.session.get('filter_criterias') != null %}
											{% if app.request.session.get('filter_criterias').get(k) != null %}
												{% if app.request.session.get('filter_criterias').get(k)[0] != '' %}
													{% set inputMinValue = app.request.session.get('filter_criterias').get(k)[0] %}
												{% endif %}
											{% endif %}
										{% endif %}
										<input type="number" name="{{ k }}[]" id="{{ k~'_Min' }}" value="{{ inputMinValue }}">
									</li>
									<li>
										<label for="{{ k~'_Max' }}">Max</label>
										{% set inputMaxValue = '' %}
										{% if app.request.session.get('filter_criterias') != null %}
											{% if app.request.session.get('filter_criterias').get(k) != null %}
												{% if app.request.session.get('filter_criterias').get(k)[1] != '' %}
													{% set inputMaxValue = app.request.session.get('filter_criterias').get(k)[1] %}
												{% endif %}
											{% endif %}
										{% endif %}
										<input type="number" name="{{ k }}[]" id="{{ k~'_Max' }}" value="{{ inputMaxValue }}">
									</li>
								</ul>
							{% endif %}
						</li>
					{% endif %}
				{% endfor %}
			</ul>
		</div>
	</form>
</div>

templates/private_area/_header_user.html.twig
<div class="top-right-user">
	{% if app.user %}
		<h3>{{ app.user.firstname }} {{ app.user.lastname }}</h3>
		<i class="fa fa-user" title="{{ app.user.firstname }} {{ app.user.lastname }}"></i>
		{{ render(controller("App\\Controller\\PrivateArea\\MessageController::countMessageNotRead")) }}
		<a href="{{ path('app_logout') }}" title="{{ 'logout'|trans|capitalize }}"><i class="fa fa-power-off"></i></a>
	{% endif %}
</div>

templates/private_area/_message_not_read.html.twig
{% if nbMessageNotRead > 0 %}
  <a href="{{ path('private_area_message_list') }}" title="{{ 'see messages'|trans|capitalize }}"><i class="fa fa-envelope"></i>&nbsp;{{ nbMessageNotRead }}</a>
{% endif %}

templates/private_area/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
	{% for message in app.flashes('message_alert') %}
    {{ include('include/_alert.html.twig') }}
  {% endfor %}
	<h2>Bonjour, bienvenue dans votre espace privé</h2>
	<br>
	<div class="card-private-area-container">
		<div class="card-private-area">
			<h3><i class="fa fa-envelope-square"></i>&nbsp;{{ 'my messages'|trans|capitalize }}</h3>
			<hr>
			{% if messages|length == 0 %}
				<p>{{ 'you have no new message'|trans|capitalize }}.</p>
			{% elseif messages|length == 1 %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ messages|length ~ ' ' ~ 'new message from'|trans }} :</p>
			{% else %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ messages|length ~ ' ' ~ 'new messages from'|trans }} :</p>
			{% endif %}
			<ul>
				{% for k, msg in messages|sort((a, b) => a.message.createdAt < b.message.createdAt) %}
					{% if k < 10 %}
						<li title="{{ 'see message'|trans|capitalize }}">
							<a href="{{ path('private_area_message_view', {id: msg.id}) }}">
								<i class="fa fa-user"></i>
								&nbsp;{{ msg.message.sender.lastname }} {{ msg.message.sender.firstname }}
							</a>
							<small>
								&nbsp;{{ 'on'|trans }} {{ msg.message.createdAt|date('m/d/Y') }} {{ 'at'|trans }} {{ msg.message.createdAt|date('H:i') }}
							</small>
						</li>
					{% endif %}
				{% endfor %}
				{% if messages|length > 10  %}
					<a href="{{ path('private_area_message_list') }}" title="{{ 'see all messages'|trans|capitalize }}" class="button-icon"><i class="fa fa-ellipsis-h"></i></a>
				{% endif %}
			</ul>
			<div class="d-flex justify-content-end">
				<a href="{{ path('private_area_message_list') }}" title="{{ 'see all messages'|trans|capitalize }}" class="button button-small">{{ 'see all'|trans }}</a>
			</div>
		</div>
		<div class="card-private-area">
			<h3><i class="fa fa-file-pdf-o"></i>&nbsp;{{ 'my documents'|trans|capitalize }}</h3>
			<hr>
			{% if documents|length == 0 %}
				<p>{{ 'you have no new document'|trans|capitalize }}.</p>
			{% elseif documents|length == 1 %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ documents|length ~ ' ' ~ 'new document'|trans }} :</p>
			{% else %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ documents|length ~ ' ' ~ 'new documents'|trans }} :</p>
			{% endif %}
			<ul>
				{% for k, doc in documents|filter((doc, k) => k < 10)|sort((a, b) => a.document.createdAt < b.document.createdAt) %}
					<li>
						<a href="{{ asset(doc.document.path) }}" target="_blank" title="{{ 'download document'|trans|capitalize }}">
							<i class="fa fa-download"></i>
							&nbsp;{{ doc.document.title }}
						</a>
					</li>
				{% endfor %}
				{% if documents|length > 10  %}
					<a href="{{ path('private_area_document_list') }}" title="{{ 'see all documents'|trans|capitalize }}" class="button-icon"><i class="fa fa-ellipsis-h"></i></a>
				{% endif %}
			</ul>
			<div class="d-flex justify-content-end">
				<a href="{{ path('private_area_document_list') }}" title="{{ 'see all documents'|trans|capitalize }}" class="button button-small">{{ 'see all'|trans }}</a>
			</div>
		</div>
		<div class="card-private-area">
			<h3><i class="fa fa-calendar"></i>&nbsp;{{ 'my upcoming reminders'|trans|capitalize }}</h3>
			<hr>
			{% if reminders|length == 0 %}
				<p>{{ 'you have no reminder'|trans|capitalize }}.</p>
			{% elseif reminders|length == 1 %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ reminders|length ~ ' ' ~ 'reminder'|trans }} :</p>
			{% else %}
				<p>{{ 'you have'|trans|capitalize ~ ' ' ~ reminders|length ~ ' ' ~ 'reminders'|trans }} :</p>
			{% endif %}
			<ul>
				{% for k, remind in reminders|filter((doc, k) => k < 10)|sort((a, b) => a.start < b.start) %}
					<li class="reminder-item" title="{{ remind.start|date('m/d/Y') ~ '\n' ~ remind.title ~ '\n' ~ remind.description }}" style="{{ 'background-color:' ~ remind.color }}">
						<span><i class="fa fa-calendar-check-o"></i>&nbsp;{{ remind.title }}</span>
						<small>&nbsp;{{ 'on'|trans }} {{ remind.start|date('m/d/Y') }}</small>
					</li>
				{% endfor %}
				{% if reminders|length > 10  %}
					<a href="{{ path('private_area_calendar_list') }}" title="{{ 'see all reminders'|trans|capitalize }}" class="button-icon"><i class="fa fa-ellipsis-h"></i></a>
				{% endif %}
			</ul>
			<div class="d-flex justify-content-end">
				<a href="{{ path('private_area_calendar_list') }}" title="{{ 'see all reminders'|trans|capitalize }}" class="button button-small">{{ 'see all'|trans }}</a>
			</div>
		</div>
		<div class="card-private-area">
			<h3><i class="fa fa-user-circle-o"></i>&nbsp;{{ 'my profile'|trans|capitalize }}</h3>
			<hr>
			<ul>
				<li class="profile-item"><strong>{{ 'firstname'|trans|capitalize }} :</strong>&nbsp;{{ app.user.firstname }}</li>
				<li class="profile-item"><strong>{{ 'lastname'|trans|capitalize }} :</strong>&nbsp;{{ app.user.lastname }}</li>
				<li class="profile-item"><strong>{{ 'email address'|trans|capitalize }} :</strong>&nbsp;{{ app.user.email }}</li>
				<li class="profile-item"><strong>{{ 'phone number'|trans|capitalize }} :</strong>&nbsp;{{ app.user.phoneNumber }}</li>
				<li class="profile-item"><strong>{{ 'address'|trans|capitalize }} :</strong>&nbsp;<address>{{ app.user.address }}</address></li>
			</ul>
			<div class="d-flex justify-content-end">
				<a href="{{ path('private_area_edit_profil') }}" title="{{ 'modify my personal information'|trans|capitalize }}" class="button button-small">{{ 'modify'|trans }}</a>
			</div>
		</div>
	</div>
</main>
{% endblock %}