src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $transaction_type;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $manager;

    /**
     * @ORM\Column(type="integer")
     */
    private $area;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $energy;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $GES;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity=PropertyType::class, inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property_type;

    /**
     * @ORM\OneToMany(targetEntity=Offer::class, mappedBy="property")
     */
    private $offers;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, mappedBy="property")
     */
    private $options;

    /**
     * @ORM\ManyToMany(targetEntity=Image::class, mappedBy="property")
     */
    private $images;

    public function __construct()
    {
        $this->offers = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTransactionType(): ?string
    {
        return $this->transaction_type;
    }

    public function setTransactionType(string $transaction_type): self
    {
        $this->transaction_type = $transaction_type;

        return $this;
    }

    public function getManager(): ?string
    {
        return $this->manager;
    }

    public function setManager(string $manager): self
    {
        $this->manager = $manager;

        return $this;
    }

    public function getArea(): ?int
    {
        return $this->area;
    }

    public function setArea(int $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getEnergy(): ?string
    {
        return $this->energy;
    }

    public function setEnergy(string $energy): self
    {
        $this->energy = $energy;

        return $this;
    }

    public function getGES(): ?string
    {
        return $this->GES;
    }

    public function setGES(string $GES): self
    {
        $this->GES = $GES;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPropertyType(): ?PropertyType
    {
        return $this->property_type;
    }

    public function setPropertyType(?PropertyType $property_type): self
    {
        $this->property_type = $property_type;

        return $this;
    }

    /**
     * @return Collection|Offer[]
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addOffer(Offer $offer): self
    {
        if (!$this->offers->contains($offer)) {
            $this->offers[] = $offer;
            $offer->setProperty($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): self
    {
        if ($this->offers->removeElement($offer)) {
            // set the owning side to null (unless already changed)
            if ($offer->getProperty() === $this) {
                $offer->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->addProperty($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            $image->removeProperty($this);
        }

        return $this;
    }
}

src/Entity/Property/City.php
<?php

namespace App\Entity\Property;

use App\Repository\Property\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Property::class, mappedBy="city")
     */
    private $properties;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $department;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coordinates;

    public function __construct()
    {
        $this->properties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Property[]
     */
    public function getProperties(): Collection
    {
        return $this->properties;
    }

    public function addProperty(Property $property): self
    {
        if (!$this->properties->contains($property)) {
            $this->properties[] = $property;
            $property->setCity($this);
        }

        return $this;
    }

    public function removeProperty(Property $property): self
    {
        if ($this->properties->removeElement($property)) {
            // set the owning side to null (unless already changed)
            if ($property->getCity() === $this) {
                $property->setCity(null);
            }
        }

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getCoordinates(): ?string
    {
        return $this->coordinates;
    }

    public function setCoordinates(string $coordinates): self
    {
        $this->coordinates = $coordinates;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Entity/Property/Property.php
<?php

namespace App\Entity\Property;

use App\Entity\User\Owner;
use App\Entity\User\Tenant;
use App\Entity\User\User;
use App\Repository\Property\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $transaction_type;

    /**
     * @ORM\Column(type="integer")
     */
    private $area;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $energy;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $ges;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity=PropertyType::class, inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property_type;

    /**
     * @ORM\OneToMany(targetEntity=Offer::class, mappedBy="property")
     */
    private $offers;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, mappedBy="property")
     */
    private $options;

    /**
     * @ORM\Column(type="integer")
     */
    private int $property_ad_count = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="manager_properties")
     */
    private $manager_property;

    /**
     * @ORM\ManyToOne(targetEntity=Owner::class, inversedBy="owner_properties")
     */
    private $owner_property;

    /**
     * @ORM\ManyToMany(targetEntity=Tenant::class, inversedBy="tenant_properties")
     */
    private $property_tenants;

    public function __construct()
    {
        $this->offers = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->property_tenants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTransactionType(): ?string
    {
        return $this->transaction_type;
    }

    public function setTransactionType(string $transaction_type): self
    {
        $this->transaction_type = $transaction_type;

        return $this;
    }

    public function getArea(): ?int
    {
        return $this->area;
    }

    public function setArea(int $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getEnergy(): ?string
    {
        return $this->energy;
    }

    public function setEnergy(string $energy): self
    {
        $this->energy = $energy;

        return $this;
    }

    public function getGes(): ?string
    {
        return $this->ges;
    }

    public function setGes(string $ges): self
    {
        $this->ges = $ges;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPropertyType(): ?PropertyType
    {
        return $this->property_type;
    }

    public function setPropertyType(?PropertyType $property_type): self
    {
        $this->property_type = $property_type;

        return $this;
    }

    /**
     * @return Collection|Offer[]
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addOffer(Offer $offer): self
    {
        if (!$this->offers->contains($offer)) {
            $this->offers[] = $offer;
            $offer->setProperty($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): self
    {
        if ($this->offers->removeElement($offer)) {
            // set the owning side to null (unless already changed)
            if ($offer->getProperty() === $this) {
                $offer->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getPropertyAdCount(): ?int
    {
        return $this->property_ad_count;
    }

    public function setPropertyAdCount(int $property_ad_count) :self
    {
        $this->property_ad_count = $property_ad_count;

        return $this;
    }

    public function getManagerProperty(): ?User
    {
        return $this->manager_property;
    }

    public function setManagerProperty(?User $manager_property): self
    {
        $this->manager_property = $manager_property;

        return $this;
    }

    public function getOwnerProperty(): ?Owner
    {
        return $this->owner_property;
    }

    public function setOwnerProperty(?Owner $owner_property): self
    {
        $this->owner_property = $owner_property;

        return $this;
    }

    /**
     * @return Collection|Tenant[]
     */
    public function getPropertyTenants(): Collection
    {
        return $this->property_tenants;
    }

    public function addPropertyTenant(Tenant $propertyTenant): self
    {
        if (!$this->property_tenants->contains($propertyTenant)) {
            $this->property_tenants[] = $propertyTenant;
        }

        return $this;
    }

    public function removePropertyTenant(Tenant $propertyTenant): self
    {
        $this->property_tenants->removeElement($propertyTenant);

        return $this;
    }
}

src/Form/PrivateArea/CalendarType.php
<?php

namespace App\Form\PrivateArea;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $colors = [
            0 => '#9510f2', 
            1 => '#049DD9', 
            2 => '#45A165', 
            3 => '#F2BF3D', 
            4 => '#EB403D', 
            5 => '#CCCCCC'
        ];
        $repeats = [
            'weekly' => 'week',
            'monthly' => 'month',
            'annual' => 'year'
        ];

        $builder
            ->add('reminder_id', HiddenType::class)
            ->add('reminder_date', TextType::class, [
                'attr' => [
                    'class' => 'form-control form-control-input',
                    'autocomplete' => 'off',
                    'pattern' => '^\d{2}\/\d{2}\/\d{2}$',
                    'placeholder' => 'jj/mm/aa'
                ],
            ])
            ->add('is_repeated', CheckboxType::class, [
                'required' => false
                ])
            ->add('frequency', ChoiceType::class, [
                'expanded' => true,
                'multiple' => false,
                'required' => false,
                'choices' => $repeats,
                'mapped' => false,
                'placeholder' => false, 
            ])
            ->add('repeat_end', TextType::class, [
                'attr' => [
                    'class' => 'form-control form-control-input',
                    'autocomplete' => 'off',
                    'pattern' => '^\d{2}\/\d{2}\/\d{2}$',
                    'placeholder' => 'jj/mm/aa',
                    'disabled' => 'disabled'
                ],
                'mapped' => false,
                'required' => false,
            ])
            ->add('title', TextType::class, [
                'attr' => ['class' => 'form-control-input'],
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'mapped' => false,
                'attr' => [
                    'class' => 'form-control-input',
                    'rows' => 5
                ],
            ])
            ->add('color', ChoiceType::class, [
                'expanded' => true,
                'multiple' => false,
                'choices' => $colors
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

templates/private_area/property/edit.html.twig
{% extends 'base.html.twig' %} {% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
  <section class="form-section-private">
		<div class="private-area-scroll-container position-center">
      {{ include('private_area/property/_form.html.twig', {button: 'modify', title: 'modify a property'|trans|upper}) }}
    </div>
	</section>
</main>
{% endblock %}
{% block javascripts %}
  <script src="{{ asset('assets/js/searchCities.js') }}"></script>
{% endblock %}

templates/private_area/property/manage_tenants.html.twig
{% extends 'base.html.twig' %} 

{% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
  <h1><i class="fa fa-user-plus"></i>&nbsp;{{ 'manage tenants for rental property no'|trans|upper }}&nbsp;{{ propertyId }}</h1>
  {{ form_start(form) }}
    <div class="form-control-group">
      {{ form_label(form.property_tenants, null, {'label': 'tenants for this property'|trans|capitalize}) }}&nbsp;<i class="fa fa-caret-right"></i>
      {{ form_widget(form.property_tenants) }}
    </div>
    <div class="form-button-submit-between">
      <a href="{{ path('referer') }}" class="button button-rounded"><i class="fa fa-arrow-left"></i>&nbsp;{{ 'back to list'|trans }}</a>
      <button type="submit" class="button button-rounded button-outline"><i class="fa fa-check"></i>&nbsp;{{'modify'|trans}}</button>
    </div>
  {{ form_end(form) }}
</main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.min.js" integrity="sha512-RtZU3AyMVArmHLiW0suEZ9McadTdegwbgtiQl5Qqo9kunkVg1ofwueXD8/8wv3Af8jkME3DDe3yLfR8HSJfT2g==" crossorigin="anonymous"></script>
<script>$('#property_manage_tenant_form_property_tenants').select2()</script>
{% endblock %}

templates/private_area/property/new.html.twig
{% extends 'base.html.twig' %} {% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
  <section class="form-section-private">
		<div class="private-area-scroll-container position-center">
      {{ include('private_area/property/_form.html.twig', {button: 'create', title: 'create new property'|trans|upper}) }}
    </div>
	</section>
</main>
{% endblock %}
{% block javascripts %}
  <script src="{{ asset('assets/js/searchCities.js') }}"></script>
{% endblock %}

templates/private_area/property/view.html.twig
{% extends 'base.html.twig' %} 

{% block title %}{{ "private area" | trans | capitalize }} - {{ "Real estate agency" | trans }} {% endblock %}

{% block bodyPrivateArea %}
{% include "private_area/_header_user.html.twig" %}
<main id="private-area-main">
	{% for message in app.flashes('message_alert') %}
    {{ include('include/_alert.html.twig') }}
  {% endfor %}
	<h2>{{'property no'|trans|capitalize}}&nbsp;{{ property.id }}</h2>
	<div class="view-informations">
		<div class="view-informations-group-1">
			<h3><i class="fa fa-list"></i>&nbsp;{{ 'general informations'|trans|capitalize }} :</h3>
			<ul>
				<li><strong>{{ 'transaction type'|trans|capitalize }} : </strong>{{ property.transactionType|trans|capitalize }}</li>
				{% if property.transactionType == 'rental' %}
					<li><strong>{{ 'status'|trans|capitalize }} : </strong>
						{{ property.propertyTenants|length > 0 ? 'rented'|trans|capitalize : 'not rented'|trans|capitalize }}&nbsp;
						<a href="" class="button-icon" style="margin: 0; font-size: 1em" title="{{ 'manage tenants'|trans|capitalize }}" data-target="#modal-confirm-manage-tenant" data-toggle="modal" data-id="{{ property.id }}" data-path="{{ path('private_area_property_manage_tenant', {id: property.id}) }}"><i class="fa fa-pencil"></i></a>
					</li>
				{% endif %}

				<li><strong>{{ 'property ad'|trans|capitalize }} : </strong>
					{{ property.propertyAdCount }}
					{% if property.propertyTenants|length == 0 %}
						<a href="{{ path('private_area_offer_new', {propertyId: property.id}) }}" class="button-icon" style="margin: 0; font-size: 1em" title="{{ 'new property ad'|trans|capitalize }}"><i class="fa fa-plus-circle"></i></a>
					{% endif %}
				</li>
				<li><strong>{{ 'city'|trans|capitalize }} : </strong>{{ property.city.zipcode }} {{ property.city.name }}</li>
				<li><strong>{{ 'type'|trans|capitalize }} : </strong>{{ property.propertyType }}</li>
				{% if property.transactionType == 'rental' %}
					<li>
						<strong>{{ 'rent'|trans|capitalize }} : </strong>
						{{ property.price|format_currency('EUR', locale='fr', attrs={rounding_mode: 'floor', fraction_digit: 0}) }}	/ {{'month'|trans}}
					</li>
				{% else %}
					<li>
						<strong>{{ 'price'|trans|capitalize }} : </strong>
						{{ property.price|format_currency('EUR', locale='fr', attrs={rounding_mode: 'floor', fraction_digit: 0}) }}
					</li>
				{% endif %}
				<li><strong>{{ 'area'|trans|capitalize }} : </strong>{{ property.area }} m²</li>
				<li><strong>{{ 'rooms'|trans|capitalize }} : </strong>{{ property.rooms }}</li>
			</ul>
			<div class="energy-ges-property-view-group">
				<h3><i class="fa fa-flash"></i>&nbsp;{{ 'Energy consumption'|trans|capitalize }} :</h3>
				<div class="property-view-energy">
					{% for letter in letters %}
						<span style="{{ letter == property.energy ? 'font-size: 1.4em;' : '' }}">
							{% if letter == property.energy %}
								<i class="fa fa-caret-up"></i>
							{% endif %}
							{{ letter }}
						</span>
					{% endfor %}
				</div>
				<h3><i class="fa fa-tree"></i>&nbsp;{{ 'Greenhouse gas emission'|trans|capitalize }} :</h3>
				<div class="property-view-ges">
					{% for letter in letters %}
					<span style="{{ letter == property.ges ? 'font-size: 1.4em;' : '' }}">
						{% if letter == property.ges %}
						<i class="fa fa-caret-up"></i>
						{% endif %}
						{{ letter }}
					</span>
					{% endfor %}
				</div>
				<h3><i class="fa fa-cog"></i>&nbsp;{{ 'options'|trans|capitalize }} :</h3>
				<div class="property-view-options">
					{% for option in property.options %}
						<span>{{ option.name|capitalize }}</span>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="view-informations-group-2">
			<h3><i class="fa fa-address-card-o"></i>&nbsp;{{ 'owner informations'|trans|capitalize }} :</h3>
			<ul>
				<h6><i class="fa fa-user"></i>&nbsp;{{ 'owner no'|trans|capitalize }} {{ property.ownerProperty.id }} :</h6>
				<li><strong>{{ 'lastname'|trans|capitalize }} : </strong>{{ property.ownerProperty.lastname }}</li>
				<li><strong>{{ 'firstname'|trans|capitalize }} : </strong>{{ property.ownerProperty.firstname }}</li>
				<li><strong>{{ 'address'|trans|capitalize }} : </strong>{{ property.ownerProperty.address }}</li>
				<li><strong>{{ 'email'|trans|capitalize }} : </strong>{{ property.ownerProperty.email }}</li>
				<li><strong>{{ 'phone number'|trans|capitalize }} : </strong>{{ property.ownerProperty.phoneNumber }}</li>
			</ul>
			{% if property.transactionType == 'rental' and property.propertyTenants|length > 0 %}
			<h3><i class="fa fa-address-book-o"></i>&nbsp;{{ 'tenants informations'|trans|capitalize }} :</h3>
				{% for tenant in property.propertyTenants %}
					<ul>
						<h6><i class="fa fa-user"></i>&nbsp;{{ 'tenant no'|trans|capitalize }} {{ tenant.id }} :</h6>
						<li><strong>{{ 'lastname'|trans|capitalize }} : </strong>{{ tenant.lastname }}</li>
						<li><strong>{{ 'firstname'|trans|capitalize }} : </strong>{{ tenant.firstname }}</li>
						<li><strong>{{ 'address'|trans|capitalize }} : </strong>{{ tenant.address }}</li>
						<li><strong>{{ 'email'|trans|capitalize }} : </strong>{{ tenant.email }}</li>
						<li><strong>{{ 'phone number'|trans|capitalize }} : </strong>{{ tenant.phoneNumber }}</li>
					</ul>
				{% endfor %}
			{% endif %}
			<div class="form-button-submit-right">
				<a href="{{ path('private_area_property_list') }}" class="button button-rounded button-small"><i class="fa fa-arrow-left"></i>&nbsp;{{ 'back to list'|trans }}</a>
			</div>
		</div>
	</div>
</main>
<div class="modal" id="modal-confirm-manage-tenant" role="dialog">
	<div class="modal-content">
		<a href="#" class="modal-close fa fa-close" role="button" data-dismiss="dialog"></a>
		<div class="modal-header">
		<h3><i class="fa fa-warning"></i>&nbsp;{{ 'change the status of a rental property'|trans|capitalize }}</h3>
		</div>
		<div class="modal-body">
			<p>{{ 'you are about to change the status of a rental property.'|trans|capitalize }}</p>
			<br>
			<ol>
				<li>{{ 'rented status: the property has at least one attached tenant, if it has an ad it is automatically deleted and you can no longer create one.'|trans|capitalize }}</li>
				<li>{{ 'not-rented status: the property does not have any attached tenant, you can create an ad'|trans|capitalize }}</li>
			</ol>
			<p>{{ 'you can cancel or continue.'|trans|capitalize }}</p>
		</div>
		<div class="modal-footer">
			<button class="button button-rounded button-outline" role="button" data-dismiss="dialog"><i class="fa fa-close"></i>&nbsp;{{'cancel'|trans}}</button>
			<a id="continue-button" role="button" class="button button-rounded"><i class="fa fa-check"></i>&nbsp;{{'continue'|trans}}</a>
		</div>
	</div>
</div>
{% endblock %}